repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'
    hooks:
      - id: poetry-check
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "main-requirements.txt"]

  - repo: local
    hooks:
      - id: black
        name: black
        description: This hook runs black within our project's environment.
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true

      - id: isort
        name: isort
        description: This hook runs isort within our project's environment.
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true

      - id: ruff
        name: ruff
        description: Run ruff linting
        entry: poetry run ruff check --force-exclude
        language: system
        'types_or': [python, pyi]
        require_serial: true
        args: [--fix, --exit-non-zero-on-fix]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [ruff, black, isort]  # pre-commit.ci doesn't support running under poetry right now.
  submodules: false
