[tool.poetry]
name = "python-template"
version = "1.1.0"
description = "A template project for Python applications."
authors = ["Chris Lovering <chris.lovering.95@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.11.*"

pydantic = "*"

[tool.poetry.group.linting.dependencies]
black = "*"
pre-commit = "*"
ruff = "*"

[tool.poetry.group.dev.dependencies]
poetry-plugin-export = "*"
taskipy = "*"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python -m app"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"

[tool.ruff]
target-version = "py311"
extend-exclude = [".cache"]
ignore = [
    "ANN002", "ANN003",
    "D100", "D104", "D105", "D107", "D203", "D212", "D214", "D215", "D416",
]
line-length = 120
select = ["ALL"]
