on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python Dependencies
        uses: HassanAbouelela/actions/setup-python@setup-python_v1.4.0
        with:
          python_version: "3.11"
          install_args: "--only linting"

      - name: Ensure main-requirements.txt is up to date
        shell: bash
        run: |
          poetry export -f requirements.txt --output temp-requirements.txt -vvv

          if ! cmp -s "main-requirements.txt" "temp-requirements.txt"; then
            echo "::error file=main-requirements.txt,title=Requirements out of date!::Run 'poetry export -f requirements.txt --output main-requirements.txt'"
            exit 1
          fi

      - name: Run pre-commit hooks
        run: SKIP=ruff pre-commit run --all-files

      # Run `ruff` using github formatting to enable automatic inline annotations.
      - name: Run ruff
        run: "ruff check --format=github ."
