name: main

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-inputs:
    runs-on: ubuntu-latest
    outputs:
      sha-tag: ${{ steps.sha-tag.outputs.sha-tag }}
    steps:
      - name: Create SHA Container Tag
        id: sha-tag
        run: |
          tag=$(cut -c 1-7 <<< $GITHUB_SHA)
          echo "sha-tag=$tag" >> $GITHUB_OUTPUT
      # docker/build-push-action doesn't allow capital letters in the URL
      - name: Get repo in lowercase
        run: |
          echo "lower-repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
  lint:
    uses: ./.github/workflows/lint.yaml

  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/build.yaml
    needs:
      - lint
      - generate-inputs
    with:
      sha-tag: ${{ needs.generate-inputs.outputs.sha-tag }}
      lower-repo: ${{ needs.generate-inputs.outputs.lower-repo }}
